name = "is-called"
type = "webpack"
account_id = "93ff523463821408b1e16cb2a064f3c7"
workers_dev = true
routes = ["*.meat.iscalled.com/*", "*.male.iscalled.com/*", "*.female.iscalled.com/*", "*.group.iscalled.com/*", "*.infant.iscalled.com/*"]
zone_id = "987cf8f21aadb44283455a6d5ca2183d"
kv_namespaces = [  { binding = "CALLED", id = "e2ad63645fb440739b4166a1c077dff2"}]
vars = {CSV_IN = "build/wikipedia.csv", JSON_OUT = "build/animals.json"}

[site]
bucket = "./public"
entry-point = "./workers-site"
