type = "webpack"
account_id = "93ff523463821408b1e16cb2a064f3c7"
workers_dev = true

[site]
bucket = "./public"
entry-point = "./workers-site"

[env.production]
name = "is-called"
zone_id = "987cf8f21aadb44283455a6d5ca2183d"
routes = ["iscalled.com/*", "what.iscalled.com/*","*.meat.iscalled.com/*", "*.male.iscalled.com/*", "*.female.iscalled.com/*", "*.group.iscalled.com/*", "*.infant.iscalled.com/*"]
kv_namespaces = [  { binding = "CALLED", id = "e2ad63645fb440739b4166a1c077dff2"},  { binding = "MSG_QUEUE", id = "cc91fadb56c04e54b3c99300e83f28f9"},{ binding = "__STATIC_CONTENT", id = "b834198869444f92b04cffb66d0d818b"}]

[env.staging]
name = "are-called"
zone_id = "b987a4fb83d3bb403107b8a8cdda3226"
routes = ["arecalled.com/*", "what.arecalled.com/*","*.meat.arecalled.com/*", "*.male.arecalled.com/*", "*.female.arecalled.com/*", "*.group.arecalled.com/*", "*.infant.arecalled.com/*"]
kv_namespaces = [  { binding = "CALLED", id = "e2ad63645fb440739b4166a1c077dff2"},  { binding = "MSG_QUEUE", id = "cc91fadb56c04e54b3c99300e83f28f9"},{ binding = "__STATIC_CONTENT", id = "b834198869444f92b04cffb66d0d818b"}]
